"use client";

import { motion, useReducedMotion } from "framer-motion";
import { fadeUpVariants, staggerContainerVariants } from "@/lib/motion";

// Corporate details
const megatrends = [
    {
        title: "Automotive Cockpit",
        desc: "Custom HMI systems, hypervisors, Android Automotive OS (AAOS), dual-screen control modules, and OTA software layers.",
        color: "var(--violet-mid)"
    },
    {
        title: "Autonomous Systems",
        desc: "ADAS sensor fusion (cameras, radar, lidar), lane keeping, autonomous pathing, and computer vision classifiers.",
        color: "var(--rose)"
    },
    {
        title: "System Engg & Consulting",
        desc: "Requirements modeling, architecture specification (AUTOSAR), system integration, and verification & validation.",
        color: "var(--blue)"
    },
    {
        title: "Safety & Security",
        desc: "ISO 26262 functional safety compliance, MISRA C/C++ static analysis, and secure cybersecurity bootloaders.",
        color: "var(--mint)"
    }
];

const reasons = [
    "Services Standard - Consulting Approach",
    "Committed to Create & Demonstrate Value Generated by our Services",
    "Flexible Models for Business and Engagement",
    "Extensive Experience in Global, Complex Technology Architectures",
    "Ecosystem Partner Network for providing end-to-end Solutions"
];

// Profile Avatar Monogram Component to replace static photos with premium neon initials
function ProfileAvatar({ name, role }: { name: string; role: string }) {
    const initials = name.split(" ").map(n => n[0]).join("");
    // Use role to assign a consistent gradient
    let grad = "var(--grad-violet)";
    if (role.includes("CEO") || role.includes("Founder")) grad = "linear-gradient(135deg, #EC4899 0%, #8B5CF6 100%)";
    else if (role.includes("Advisor") || role.includes("Board")) grad = "linear-gradient(135deg, #3B82F6 0%, #EC4899 100%)";
    else grad = "linear-gradient(135deg, #10B981 0%, #3B82F6 100%)";

    return (
        <div style={{
            width: "90px",
            height: "90px",
            borderRadius: "50%",
            background: grad,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            fontSize: "1.6rem",
            fontWeight: 700,
            color: "#ffffff",
            margin: "0 auto 20px",
            boxShadow: "0 8px 24px rgba(0, 0, 0, 0.3), 0 0 15px rgba(255,255,255,0.1)",
            border: "2px solid rgba(255, 255, 255, 0.1)",
            position: "relative"
        }}>
            {initials}
            <div style={{
                position: "absolute",
                inset: "-4px",
                borderRadius: "50%",
                border: "1px solid rgba(255,255,255,0.06)",
                pointerEvents: "none"
            }} />
        </div>
    );
}

export default function AboutPage() {
    const shouldReduce = useReducedMotion();

    return (
        <div style={{ paddingBottom: "100px" }}>

            {/* Page Hero */}
            <section className="page-hero" aria-labelledby="about-heading">
                <div className="hero-glow" style={{ opacity: 0.15 }} />
                <div className="container">
                    <motion.div
                        variants={staggerContainerVariants}
                        initial="hidden"
                        animate="visible"
                    >
                        <motion.div variants={fadeUpVariants(shouldReduce)}>
                            <span className="badge" style={{ marginBottom: "24px" }}>About Us</span>
                        </motion.div>
                        <motion.h1 id="about-heading" variants={fadeUpVariants(shouldReduce)} style={{ marginBottom: "20px" }}>
                            About Company
                        </motion.h1>
                        <motion.p className="lead" variants={fadeUpVariants(shouldReduce)} style={{ maxWidth: "580px" }}>
                            Samsan Labs (Samsan Technoche Labs) is a technology reimagined systems design house powering global automotive megatrends.
                        </motion.p>
                    </motion.div>
                </div>
            </section>

            {/* Technoche Labs Intro Section */}
            <section className="section compact" style={{ borderTop: "1px solid var(--border)" }}>
                <div className="container">
                    <div className="about-two-col" style={{ display: "grid", gridTemplateColumns: "1.2fr 1fr", gap: "60px", alignItems: "center" }}>
                        <div>
                            <span className="badge rose" style={{ marginBottom: "16px" }}>Company Overview</span>
                            <h2 style={{ fontSize: "2.2rem", fontWeight: 700, marginBottom: "24px", color: "#ffffff", letterSpacing: "-0.025em" }}>
                                SAMSAN Technoche Labs
                            </h2>
                            <p style={{ fontSize: "1.05rem", lineHeight: "1.8", color: "var(--text-primary)", marginBottom: "20px" }}>
                                Samsan Labs is a leading technology company specializing in Software Defined Vehicles, Connected Mobility, ADAS, and Automotive AI. We deliver high-end digital transformation platforms and embedded technologies.
                            </p>
                            <p style={{ fontSize: "0.95rem", lineHeight: "1.8", color: "var(--text-secondary)" }}>
                                Our focus is to build safety-critical software that is always reliable, secure, and ready for production, bringing systems engineering excellence to automotive megatrends.
                            </p>
                        </div>

                        {/* Interactive Side Graphic */}
                        <div style={{
                            background: "rgba(13, 19, 35, 0.45)",
                            border: "1px solid rgba(255, 255, 255, 0.06)",
                            borderRadius: "var(--radius-lg)",
                            padding: "40px",
                            display: "flex",
                            alignItems: "center",
                            justifyContent: "center",
                            minHeight: "300px",
                            position: "relative",
                            overflow: "hidden",
                            backgroundImage: "url('/images/ai_digital_tech.png')",
                            backgroundSize: "cover",
                            backgroundPosition: "center",
                            boxShadow: "0 20px 40px rgba(0,0,0,0.3)"
                        }}>
                            <div style={{
                                position: "absolute",
                                inset: 0,
                                background: "linear-gradient(to top, rgba(10,15,28,0.9) 0%, rgba(10,15,28,0.3) 100%)",
                                zIndex: 1
                            }} />
                            <div style={{ position: "relative", zIndex: 2, textAlign: "center" }}>
                                <span className="badge" style={{ background: "rgba(255,255,255,0.1)", backdropFilter: "blur(4px)" }}>AI & Digital Embedded Technologies</span>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* Automotive Megatrends */}
            <section className="section compact" style={{ borderTop: "1px solid var(--border)", background: "rgba(10,15,28,0.2)" }}>
                <div className="container">
                    <div style={{ textAlign: "center", marginBottom: "48px" }}>
                        <span className="badge mint" style={{ marginBottom: "16px" }}>Core Competencies</span>
                        <h2 style={{ fontSize: "2.2rem", fontWeight: 700 }}>Our Strong Focus in Automotive Megatrends</h2>
                    </div>

                    <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))", gap: "24px" }}>
                        {megatrends.map((trend) => (
                            <div
                                key={trend.title}
                                style={{
                                    background: "rgba(13, 19, 35, 0.45)",
                                    border: "1px solid rgba(255, 255, 255, 0.05)",
                                    borderRadius: "var(--radius)",
                                    padding: "32px 28px",
                                    position: "relative",
                                    overflow: "hidden"
                                }}
                            >
                                <div style={{
                                    width: "4px",
                                    height: "32px",
                                    background: trend.color,
                                    position: "absolute",
                                    left: 0,
                                    top: "32px",
                                    borderRadius: "0 4px 4px 0"
                                }} />
                                <h3 style={{ fontSize: "1.2rem", color: "#ffffff", marginBottom: "14px", fontWeight: 600 }}>{trend.title}</h3>
                                <p style={{ fontSize: "0.85rem", lineHeight: "1.65", color: "var(--text-secondary)" }}>{trend.desc}</p>
                            </div>
                        ))}
                    </div>

                    {/* Cinematic Visual - Automotive Cockpit */}
                    <div style={{
                        marginTop: "48px",
                        width: "100%",
                        height: "350px",
                        borderRadius: "var(--radius-lg)",
                        backgroundImage: "url('/images/auto_cockpit_sys.png')",
                        backgroundSize: "cover",
                        backgroundPosition: "center",
                        position: "relative",
                        overflow: "hidden",
                        border: "1px solid rgba(255,255,255,0.06)",
                        boxShadow: "0 20px 40px rgba(0,0,0,0.4)"
                    }}>
                        <div style={{
                            position: "absolute", inset: 0,
                            background: "linear-gradient(to top, rgba(10,15,28,0.95) 0%, rgba(10,15,28,0.1) 100%)"
                        }} />
                        <div style={{
                            position: "absolute", bottom: "32px", left: "32px", right: "32px"
                        }}>
                            <span className="badge violet" style={{ marginBottom: "12px" }}>Automotive Cockpit Systems</span>
                            <h3 style={{ fontSize: "1.6rem", color: "#ffffff", fontWeight: 600 }}>Next-Gen Hyper-Modern Cockpit Ecosystems</h3>
                        </div>
                    </div>
                </div>
            </section>

            {/* Vision & Why Choose Us */}
            <section className="section compact" style={{ borderTop: "1px solid var(--border)" }}>
                <div className="container">
                    <div style={{ display: "grid", gridTemplateColumns: "1.1fr 1fr", gap: "60px", alignItems: "start" }}>
                        
                        {/* Vision Card */}
                        <div style={{
                            background: "linear-gradient(135deg, rgba(22, 30, 53, 0.5) 0%, rgba(27, 36, 64, 0.5) 100%)",
                            border: "1px solid rgba(255, 255, 255, 0.06)",
                            borderRadius: "var(--radius-lg)",
                            padding: "44px",
                            boxShadow: "0 15px 35px rgba(0,0,0,0.2)"
                        }}>
                            <span className="badge" style={{ marginBottom: "20px" }}>Our Vision</span>
                            <h2 style={{ fontSize: "1.8rem", fontWeight: 700, color: "#ffffff", marginBottom: "20px", lineHeight: "1.3" }}>
                                To design safe, connected, and intelligent systems that power the vehicle of the future.
                            </h2>
                            <p style={{ fontSize: "0.95rem", lineHeight: "1.7", color: "var(--text-secondary)" }}>
                                SAMSAN bridges the gap between hardware restrictions and complex software layers. We are committed to engineering platforms that meet the highest functional safety standards while driving agile, digital-first feature delivery.
                            </p>
                            <div style={{
                                marginTop: "32px",
                                height: "200px",
                                borderRadius: "var(--radius-sm)",
                                backgroundImage: "url('/images/embedded_engineering.png')",
                                backgroundSize: "cover",
                                backgroundPosition: "center",
                                border: "1px solid rgba(255,255,255,0.1)"
                            }} />
                        </div>

                        {/* Why Choose Us */}
                        <div>
                            <span className="badge rose" style={{ marginBottom: "16px" }}>Why Choose Us</span>
                            <h2 style={{ fontSize: "1.8rem", fontWeight: 700, marginBottom: "24px", color: "#ffffff" }}>Engineering Integrity</h2>
                            <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
                                {reasons.map((reason, idx) => (
                                    <div
                                        key={idx}
                                        style={{
                                            display: "flex",
                                            gap: "16px",
                                            background: "rgba(13, 19, 35, 0.3)",
                                            border: "1px solid rgba(255,255,255,0.04)",
                                            borderRadius: "var(--radius-sm)",
                                            padding: "16px 20px",
                                            alignItems: "center"
                                        }}
                                    >
                                        <div style={{
                                            width: "24px", height: "24px",
                                            borderRadius: "50%",
                                            background: "rgba(124, 58, 237, 0.15)",
                                            color: "var(--violet-mid)",
                                            display: "flex", alignItems: "center", justifyContent: "center",
                                            flexShrink: 0,
                                            fontSize: "0.8rem",
                                            fontWeight: 700
                                        }}>
                                            ✓
                                        </div>
                                        <p style={{ fontSize: "0.88rem", color: "var(--text-primary)", lineHeight: "1.4" }}>{reason}</p>
                                    </div>
                                ))}
                            </div>
                        </div>

                    </div>
                </div>
            </section>

            {/* Leadership & Team Section */}
            <section className="section compact" style={{ borderTop: "1px solid var(--border)", background: "rgba(10,15,28,0.1)" }}>
                <div className="container">
                    
                    {/* Header */}
                    <div style={{ textAlign: "center", marginBottom: "64px" }}>
                        <span className="badge" style={{ marginBottom: "16px" }}>Our Leadership</span>
                        <h2 style={{ fontSize: "2.4rem", fontWeight: 700, letterSpacing: "-0.025em" }}>Team Management</h2>
                        <p className="lead" style={{ maxWidth: "540px", margin: "12px auto 0" }}>
                            Meet the systems architects, advisory board, and key operations leaders steering SAMSAN Technoche Labs.
                        </p>
                    </div>

                    {/* CEO Tier */}
                    <div style={{ display: "flex", justifyContent: "center", marginBottom: "64px" }}>
                        <motion.div
                            whileHover={{ y: -5 }}
                            style={{
                                background: "rgba(22, 30, 53, 0.5)",
                                border: "2px solid rgba(139, 92, 246, 0.25)",
                                borderRadius: "var(--radius-lg)",
                                padding: "40px 60px",
                                textAlign: "center",
                                maxWidth: "340px",
                                boxShadow: "0 15px 35px rgba(0,0,0,0.3)"
                            }}
                        >
                            <ProfileAvatar name="Prashant Junghare" role="Founder & CEO" />
                            <h3 style={{ fontSize: "1.3rem", color: "#ffffff", fontWeight: 700 }}>Prashant Junghare</h3>
                            <span style={{
                                fontFamily: "var(--font-mono)",
                                fontSize: "10px",
                                color: "var(--violet-mid)",
                                textTransform: "uppercase",
                                letterSpacing: "0.1em",
                                fontWeight: 600,
                                display: "block",
                                marginTop: "6px"
                            }}>
                                Founder & CEO
                            </span>
                        </motion.div>
                    </div>

                    {/* Advisors Tier (2 Columns) */}
                    <div style={{ marginBottom: "64px" }}>
                        <h3 style={{ textAlign: "center", fontSize: "1.1rem", textTransform: "uppercase", letterSpacing: "0.1em", color: "var(--text-muted)", marginBottom: "32px", fontFamily: "var(--font-mono)" }}>
                            Board Of Advisors
                        </h3>
                        <div style={{ display: "flex", justifyContent: "center", gap: "24px", flexWrap: "wrap" }}>
                            {[
                                { name: "John Scott", role: "Board / Advisor" },
                                { name: "Dr. Anil Sharma", role: "Board / Advisor" }
                            ].map((adv) => (
                                <motion.div
                                    key={adv.name}
                                    whileHover={{ y: -5 }}
                                    style={{
                                        background: "rgba(13, 19, 35, 0.4)",
                                        border: "1px solid rgba(255, 255, 255, 0.05)",
                                        borderRadius: "var(--radius-lg)",
                                        padding: "32px",
                                        textAlign: "center",
                                        minWidth: "260px",
                                        boxShadow: "0 10px 25px rgba(0,0,0,0.2)"
                                    }}
                                >
                                    <ProfileAvatar name={adv.name} role={adv.role} />
                                    <h4 style={{ fontSize: "1.15rem", color: "#ffffff", fontWeight: 600 }}>{adv.name}</h4>
                                    <span style={{ fontSize: "0.82rem", color: "var(--text-secondary)", marginTop: "4px", display: "block" }}>{adv.role}</span>
                                </motion.div>
                            ))}
                        </div>
                    </div>

                    {/* Leaders Tier (6 Columns) */}
                    <div>
                        <h3 style={{ textAlign: "center", fontSize: "1.1rem", textTransform: "uppercase", letterSpacing: "0.1em", color: "var(--text-muted)", marginBottom: "32px", fontFamily: "var(--font-mono)" }}>
                            Leaders & Key Members
                        </h3>
                        <div style={{
                            display: "grid",
                            gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
                            gap: "24px"
                        }}>
                            {[
                                { name: "Rohan Patil", role: "Embedded Systems Director" },
                                { name: "V. Sharma", role: "Digital Transformation Lead" },
                                { name: "Vikram Joshi", role: "Chief Data Scientist" },
                                { name: "Dr. Tarun Mishra", role: "Engineering Director" },
                                { name: "Amit Ranawat", role: "Digital Marketing Lead" },
                                { name: "Sumit Goel", role: "Accountant / Finance Lead" }
                            ].map((leader) => (
                                <motion.div
                                    key={leader.name}
                                    whileHover={{ y: -5 }}
                                    style={{
                                        background: "rgba(13, 19, 35, 0.35)",
                                        border: "1px solid rgba(255, 255, 255, 0.04)",
                                        borderRadius: "var(--radius)",
                                        padding: "28px 20px",
                                        textAlign: "center",
                                        boxShadow: "0 8px 20px rgba(0,0,0,0.15)"
                                    }}
                                >
                                    <ProfileAvatar name={leader.name} role={leader.role} />
                                    <h4 style={{ fontSize: "1.1rem", color: "#ffffff", fontWeight: 600 }}>{leader.name}</h4>
                                    <span style={{ fontSize: "0.78rem", color: "var(--text-secondary)", marginTop: "4px", display: "block" }}>{leader.role}</span>
                                </motion.div>
                            ))}
                        </div>
                    </div>

                </div>
            </section>

        </div>
    );
}
